name: "Build stage"

on:
  workflow_call:
    inputs:
      build_datetime:
        description: "Build datetime, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_timestamp:
        description: "Build timestamp, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_epoch:
        description: "Build epoch, set by the CI/CD pipeline workflow"
        required: true
        type: string
      commit_hash:
        description: "Commit hash, set by the CI/CD pipeline workflow"
        required: true
        type: string
      environment:
        description: "The deployment environment"
        required: true
        type: string
      workspace:
        description: "The name of the workspace to build the application into"
        required: true
        type: string
      version:
        description: "Version of the software, set by the CI/CD pipeline workflow"
        required: true
        type: string
      repo_name:
        description: "The name of the Git repo"
        required: true
        type: string

jobs:
  build-lambda-zip:
    name: "Build Lambda Zip"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Build Python Packages"
        run: make build
        env:
          REPO_NAME: ${{ inputs.repo_name }}

      - name: Configure AWS Credentials
        uses: NHSDigital/uec-dos-management/.github/actions/configure-credentials@latest
        with:
          aws_account_id: ${{ secrets.ACCOUNT_ID }}
          aws_region: ${{ vars.AWS_REGION }}
          multi_domain: false

      - name: "Publish Python Packages"
        run: make publish
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          COMMIT_HASH: ${{ inputs.commit_hash }}
          ENVIRNOMENT: ${{ inputs.environment }}
          WORKSPACE: ${{ inputs.workspace }}
          REPO_NAME: ${{ inputs.repo_name }}
